[project]
authors = ["Landung 'Don' Setiawan <landungs@uw.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "lunch-and-learn"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]
start = "jupyter lab"

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.3.1,<5"
pixi-kernel = ">=0.5.1,<0.6"
ipykernel = ">=6.29.5,<7"
